MOSIP-20798 Unable to detect bio match even after changing abis.return.duplicate=true
mosip/mosip-mock-services pull request #173
Opened 2022-04-05 12:34 UTC by NishantKumar4559

2022-04-06 04:40 UTC, MonobikashDas requested changes

2022-04-06 04:40 UTC, MonobikashDas commented on mock-abis/src/main/java/io/mosip/proxy/abis/controller/ProxyAbisConfigController.java
> +	private void postConstruct() {
postconstruct should be in the service method since we are using this new duplicate in service itself.

2022-04-06 04:40 UTC, MonobikashDas commented on mock-abis/src/main/java/io/mosip/proxy/abis/service/ProxyAbisConfigService.java
> +	public Boolean getNewDuplicate();
no need of this method here. only setNewDuplicate() method is enough

2022-04-06 04:40 UTC, MonobikashDas commented on mock-abis/src/main/java/io/mosip/proxy/abis/service/impl/ProxyAbisConfigServiceImpl.java
> +	public Boolean getNewDuplicate() {
this is not what we discussed. Where are we using this new duplicate? why did we introduce this new duplicate?

2022-09-21 07:35 UTC, gsasikumar commented
Pending to resolve comments too long.

2022-09-21 07:35 UTC, closed without merging